_target_: src.models.classifier.Classifier

backbone_path: set/me/please.pkl

class_head:
  _target_: mltools.mltools.transformers.ClassAttentionPooling
  _partial_: true
  num_layers: 2
  dim: 128
  layer_config:
    attn_config:
      num_heads: 4
    ff_config:
      mult: 1
      dropout: 0.2

optimizer:
  _target_: mltools.mltools.optimisers.AdamWS
  _partial_: True
  lr: 5.0e-4
  betas: [0.9, 0.95]
  weight_decay: 0.01

scheduler:
  _target_: src.models.utils.linear_warmup_cosine_decay
  _partial_: True
  warmup_steps: 1_000
  total_steps: 100_000
