_target_: src.data.streamable.StreamModule
train_path: /srv/fast/share/rodem/JetClassH5/train_100M_combined.h5
val_path: /srv/fast/share/rodem/JetClassH5/val_5M_combined.h5
test_path: /srv/fast/share/rodem/JetClassH5/test_5M_combined.h5
num_csts : 32
n_classes: 10
num_workers: 2
batch_size: 1000
pin_memory: True
transforms:
  - _target_: src.data.preprocessing.mask_batch
    _partial_: True
    mask_fraction: 0.4
  - _target_: src.data.preprocessing.preprocess_batch
    _partial_: True
    cst_fn:
      _target_: joblib.load
      filename: ${root_dir}/resources/cst_quantiles.joblib
    jet_fn:
      _target_: joblib.load
      filename: ${root_dir}/resources/jet_quantiles.joblib
  - _target_: src.data.preprocessing.tokenize_batch
    _partial_: True
    token_fn:
      _target_: torch.load
      f: ${root_dir}/resources/kmeans.pkl
