defaults:
  - jetclass

# Load the same as datamodule/jetclass.yaml but add tokenization step to the transforms
transforms:
  - _target_: src.data.preprocessing.preprocess_batch
    _partial_: True
    cst_fn:
      _target_: joblib.load
      filename: ${root_dir}/resources/cst_quantiles_${datamodule.num_csts}.joblib
    jet_fn:
      _target_: joblib.load
      filename: ${root_dir}/resources/jet_quantiles.joblib
  - _target_: src.data.preprocessing.tokenize_batch
    _partial_: True
    token_fn:
      _target_: torch.load
      f: ${root_dir}/resources/kmeans_${datamodule.num_csts}.pkl
